# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20160707_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 7, 6, 17, 34, 54, 926707, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
